services:
  - type: web
    name: barberia-app
    env: python
    plan: free

    # 1) Construye el entorno, instala dependencias y corre migrations
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py makemigrations --no-input &&
      python manage.py migrate --no-input

    # 2) Arranca tu aplicación
    startCommand: >
      gunicorn barber.wsgi:application --bind 0.0.0.0:$PORT

    autoDeploy: true

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: barber.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgresql://barberia_db_4vmu_user:B3RzUQWUK16eBvy16MHarM30QUQij9St@dpg-d19hf4ripnbc73el5qog-a.ohio-postgres.render.com/barberia_db_4vmu
      # Datos para crear superusuario en build (opcional)
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@tudominio.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: UnaContrasenaSegura123
