services:
  - type: web
    name: barberia-app
    env: python
    plan: free

    # 1) Instala las dependencias
    buildCommand: "pip install -r requirements.txt"

    # 2) Corre migraciones y crea el superusuario antes del despliegue
    preDeployCommand: |
      python manage.py migrate --no-input
      python manage.py createsu
      python manage.py collectstatic --noinput

    # 3) Arranca tu aplicación en el puerto asignado por Render
    startCommand: "gunicorn barber.wsgi:application --bind 0.0.0.0:$PORT"

    autoDeploy: true

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: barber.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgresql://barberia_db_4vmu_user:B3RzUQWUK16eBvy16MHarM30QUQij9St@dpg-d19hf4ripnbc73el5qog-a.ohio-postgres.render.com/barberia_db_4vmu
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@tudominio.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: UnaContrasenaSegura123
