services:
  - type: web
    name: barberia-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn barber.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: barber.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
