# Generated by Django 5.2.3 on 2025-06-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='barberia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.barberia'),
        ),
    ]
