# Generated by Django 5.2.3 on 2025-06-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cita_barbero_alter_servicio_barberia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barbero'),
        ),
    ]
