# Generated by Django 5.2.3 on 2025-07-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cita_barbero'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='barbero',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
